pipeline {
   agent any
   environment {
              CREDS= 'ssh_for_jenkins'
       //     VDS_TOKEN     = credentials('clo')

       //
        }

  stages() {
    stage('Test1' ) {
      steps {
        script {
          sh 'echo HELLO'
          sh 'pwd && ls -li'
          withCredentials([sshUserPrivateKey(credentialsId: CREDS,
                                            keyFileVariable: 'JENKINS_PRIVATE_KEY', passphraseVariable: 'PASSPHRASE',
                                             usernameVariable: 'USERNAME')]) {

          playbook_name = "ping.yml"
          // tags='createnginx'
          ansiblePlaybook extras:   "  -u root --vault-password-file    ./.ansible_vault_file --private-key ${JENKINS_PRIVATE_KEY} -vv --extra-vars  \"TASK_FROM=${it} APPS=${APPS}   workspace=${WORKSPACE}   ssh_key=${JENKINS_PRIVATE_KEY} inventory_dir=\"inventories/dev/\"\" ",
          installation: 'ansible29',
          inventory: "${WORKSPACE}/ansible/inventories/dev/inventory",
          playbook: "${WORKSPACE}/ansible/${playbook_name}"


        }
        }
       }
     }
  }
  post {
      success {

          archiveArtifacts allowEmptyArchive: true, artifacts: '${WORKSPACE}/simple-back-front/front/*.zip', fingerprint: true

      }
    }

}
