pipeline {
   agent any


  stages() {
    stage('Test1' ) {
      steps {
        script {
          sh 'echo HELLO'
          sh 'pwd && ls -li'

        }
       }
     }
  }
  post {
      success {

          archiveArtifacts allowEmptyArchive: true, artifacts: '${WORKSPACE}/simple-back-front/front/*.zip', fingerprint: true

      }
    }

}
