---
- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  vars_files:
    - "{{inventory_dir}}/group_vars/geeks/main.yml"
  tasks:
  - name: Git checkout
    ping:

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: absent
      mode: '0755'

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: directory
      mode: '0755'

  - name: Install apache httpd  (state=present is optional)
    apt:
      name:
        - unzip
        - virtualenv
      state: present

  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: app.zip
      dest: /opt/shop

    # Install (Bottle) into the specified (virtualenv), inheriting none of the globally installed modules
  - pip:
      name:
        - django
        - gunicorn
      virtualenv: /opt/shop/venv
      virtualenv_python: python3

  - name: Copy file with owner and permissions
    template:
      src: shop.service
      dest: /etc/systemd/system/shop.service
      mode: '0755'

  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: stop service cron on debian, if running
    systemd:
      name: shop
      state: stopped

  - name: stop service cron on debian, if running
    systemd:
      name: shop
      state: started

  - name: Install the package "foo"
    apt:
      name: nginx
      state: present

  - name: Copy Nginx conf
    template:
      src: site.conf
      dest: /etc/nginx/sites-available/default

  - name: stop service cron on debian, if running
    service:
      name: nginx
      state: stopped

  - name: Make sure a service is running
    service:
      state: started
      name:  nginx
