---
- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:

  - name: Install the package "foo"
    apt:
      name: nginx
      state: present

  - name: Make sure a service is running
    systemd:
      state: started
      name:  nginx    
