---
- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: absent
      mode: '0755'

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: directory
      mode: '0755'

  - name: Install apache httpd  (state=present is optional)
    apt:
      name:
        - unzip
        - python-virtualenv
      state: present

  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: app.zip
      dest: /opt/shop

    # Install (Bottle) into the specified (virtualenv), inheriting none of the globally installed modules
  - pip:
      name: django
      virtualenv: /opt/shop/venv
      virtualenv_python: python3

  - name: Copy file with owner and permissions
    copy:
      src: service.systemd
      dest: /etc/systemd/system/shop.systemd
      mode: '0755'
