---
- name: Test ping host with group web
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Git checkout
    ping:

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: absent
      mode: '0755'

  - name: Create a directory if it does not exist
    file:
      path: /opt/shop
      state: directory
      mode: '0755'

  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: app.zip
      dest: /opt/shop
